### ISSUE TITLE
Does this result looks normal?

### ISSUE THREAD

**Issue by jinfagang** [TRI-ML/packnet-sfm#145]
![image](https://user-images.githubusercontent.com/21303438/120168673-ba512c00-c231-11eb-8428-81f21137382f.png)

the RGBD 3D looks weired.

**Comment by jinfagang** [comment]
the orange car almost same as ground

**Comment by VitorGuizilini-TRI** [comment]
Yeah, it is definitely off, but the depth map looks OK. How are you doing the pointcloud reconstruction?

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/120419259-ad991900-c394-11eb-950e-aca775e399c9.png)


Does this looks normal? (I think the width is not good) this is DDAD_tiny

But I fixed kitti, it looks normal now:

![image](https://user-images.githubusercontent.com/21303438/120419328-d02b3200-c394-11eb-89d0-504d95ab6db8.png)

**Comment by porwalnaman01** [comment]
@jinfagang  Hello there, did you receive this error while training, if yes then how did you solve it?

Traceback (most recent call last):
File "scripts/train.py", line 68, in
train(args.file)
File "scripts/train.py", line 63, in train
trainer.fit(model_wrapper)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 65, in fit
validation_output = self.validate(val_dataloaders, module)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 120, in validate
output = module.validation_step(batch, i, n)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 194, in validation_step
output = self.evaluate_depth(batch)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 302, in evaluate_depth
inv_depths[0], inv_depths_flipped[0], method='mean')
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/utils/depth.py", line 247, in post_process_inv_depth
B,C, H, W = inv_depth.shape
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by VitorGuizilini-TRI** [comment]
Did you solve it?
