### ISSUE TITLE
the loss of velocity is dominant

### ISSUE THREAD

**Issue by designerZhou** [TRI-ML/packnet-sfm#147]
thank you for your work ,
i use you repo to train my dataset with velocity , i only have front img at 10Hz.
when i train the model ,i found the loss is doninant by velocity loss.
i want to know how to fix this ?
thank you for your replay.

**Comment by VitorGuizilini-TRI** [comment]
You can decrease the weight of the velocity loss in the configuration file, so it is less dominant during training.
Let me know if it works!

**Comment by designerZhou** [comment]
> You can decrease the weight of the velocity loss in the configuration file, so it is less dominant during training.
> Let me know if it work
it  works,at the same time ,training more time ,the dynamic objects depth is infinite

**Comment by porwalnaman01** [comment]
@designerZhou  Hello there, did you receive this error while training, if yes then how did you solve it?

Traceback (most recent call last):
File "scripts/train.py", line 68, in
train(args.file)
File "scripts/train.py", line 63, in train
trainer.fit(model_wrapper)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 65, in fit
validation_output = self.validate(val_dataloaders, module)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 120, in validate
output = module.validation_step(batch, i, n)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 194, in validation_step
output = self.evaluate_depth(batch)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 302, in evaluate_depth
inv_depths[0], inv_depths_flipped[0], method='mean')
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/utils/depth.py", line 247, in post_process_inv_depth
B,C, H, W = inv_depth.shape
ValueError: not enough values to unpack (expected 4, got 3)
