### ISSUE TITLE
How to get proper depth from regular images

### ISSUE THREAD

**Issue by mslavescu** [TRI-ML/packnet-sfm#156]
Hi,

I setup the docker same as here:
https://github.com/TRI-ML/packnet-sfm/issues/154#issue-928707614

I wownloaded all these 4 checkpoints in /data/checkpoints
- https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/models/PackNet01_MR_semisup_CStoK.ckpt
- https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/models/ResNet18_MR_selfsup_D.ckpt
- https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/models/PackNetSAN01_HR_sup_K.ckpt
- https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/models/PackNetSAN01_HR_sup_D.ckpt

And I tested this image with PackNetSAN01_HR_sup_K.ckpt and ResNet18_MR_selfsup_D.ckpt
![image](https://user-images.githubusercontent.com/461669/123201944-b48de580-d481-11eb-853d-47c17ca080f2.png)

And I got these results:
- with PackNet01_MR_semisup_CStoK
![image](https://user-images.githubusercontent.com/461669/123202035-df783980-d481-11eb-9e32-146c82a1df98.png)
- with ResNet18_MR_selfsup_D
![image](https://user-images.githubusercontent.com/461669/123202050-e7d07480-d481-11eb-8948-543763607a73.png)

When I ran the same image with MiDaS v3 I get this result, which looks much better than those above:
![image](https://user-images.githubusercontent.com/461669/123202125-046cac80-d482-11eb-9bc2-7c15ea3374d9.png)

How can I get similar depth or better than MiDaS v3 using packnet-sfm on non KITTI images?

It works fine on KITTI tiny images as I shown here:
https://github.com/TRI-ML/packnet-sfm/issues/154#issuecomment-867254872

If I run with PackNetSAN01_HR_sup_K.ckpt I get this error:

<pre>
root@ms1-PCx0Dx:/workspace/packnet-sfm# python3 scripts/infer.py --checkpoint /data/checkpoints/PackNetSAN01_HR_sup_K.ckpt --input in/test-midas3/ --output out/test-midas3/
image_shape ()
### Preparing Model
Model: SemiSupModel
DepthNet: PackNetSlimEnc01
Traceback (most recent call last):
  File "scripts/infer.py", line 162, in <module>
    main(args)
  File "scripts/infer.py", line 129, in main
    model_wrapper = ModelWrapper(config, load_datasets=False)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 57, in __init__
    self.prepare_model(resume)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 72, in prepare_model
    self.model = setup_model(self.config.model, self.config.prepared)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 463, in setup_model
    model.add_depth_net(setup_depth_net(config.depth_net, prepared))
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 403, in setup_depth_net
    args={**config, **kwargs},
  File "/workspace/packnet-sfm/packnet_sfm/utils/load.py", line 110, in load_class_args_create
    class_type = load_class(filename, paths, concat)
  File "/workspace/packnet-sfm/packnet_sfm/utils/load.py", line 105, in load_class
    raise ValueError('Unknown class {}'.format(filename))
ValueError: Unknown class PackNetSlimEnc01
</pre>

Same issue with PackNetSAN01_HR_sup_D.ckpt:

<pre>
root@ms1-PCx0Dx:/workspace/packnet-sfm# python3 scripts/infer.py --checkpoint /data/checkpoints/PackNetSAN01_HR_sup_D.ckpt --input in/test-midas3/ --output out/test-midas3/
image_shape (384, 640)
### Preparing Model
Model: SemiSupModel
DepthNet: PackNetSlimEnc01
Traceback (most recent call last):
  File "scripts/infer.py", line 162, in <module>
    main(args)
  File "scripts/infer.py", line 129, in main
    model_wrapper = ModelWrapper(config, load_datasets=False)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 57, in __init__
    self.prepare_model(resume)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 72, in prepare_model
    self.model = setup_model(self.config.model, self.config.prepared)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 463, in setup_model
    model.add_depth_net(setup_depth_net(config.depth_net, prepared))
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 403, in setup_depth_net
    args={**config, **kwargs},
  File "/workspace/packnet-sfm/packnet_sfm/utils/load.py", line 110, in load_class_args_create
    class_type = load_class(filename, paths, concat)
  File "/workspace/packnet-sfm/packnet_sfm/utils/load.py", line 105, in load_class
    raise ValueError('Unknown class {}'.format(filename))
ValueError: Unknown class PackNetSlimEnc01
</pre>

**Comment by maliksyria** [comment]
same error here

**Comment by VitorGuizilini-TRI** [comment]
Our models were trained using driving datasets, so it's expected that they do not transfer well to these new domains. You would have to train new models on more diverse datasets (like MiDaS did), to achieve this level of accuracy.

**Comment by VitorGuizilini-TRI** [comment]
About the error, seems like the pre-trained models use a different name for the encoder, and you try explicitly setting the network in your config file during inference? The training scripts provide the correct configuration, you can use those for inference as well.
