### ISSUE TITLE
Evaluation of models

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#43]
KITTI_raw-eigen_test_files-velodyne: 0.00 images [00:00, ? images/s]
Traceback (most recent call last):
  File "scripts/eval.py", line 66, in <module>
    test(args.checkpoint, args.config, args.half)
  File "scripts/eval.py", line 61, in test
    trainer.test(model_wrapper)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 128, in test
    self.evaluate(test_dataloaders, module)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 152, in evaluate
    return module.test_epoch_end(all_outputs)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 262, in test_epoch_end
    output_data_batch, self.test_dataset, self.metrics_name)
  File "/workspace/packnet-sfm/packnet_sfm/utils/reduce.py", line 53, in all_reduce_metrics
    names = [key for key in list(output_data_batch[0][0].keys()) if key.startswith(name)]
IndexError: list index out of range
Makefile:77: recipe for target 'docker-run' failed
  

I got this error when I tried to evaluate the model.
Also, I did not use the whole dataset of Kitti and I tried to use partial data of KITTI.

**Comment by soheilAppear** [comment]
So I got why I had this issue. Since I only used some images for the evaluation part I had to change some of the text files since we i did not have those images. I think on of the files that I changed was eigen_test_files_speed.txt.
