### ISSUE TITLE
scripts to reproduce numbers in paper

### ISSUE THREAD

**Issue by hdjang** [TRI-ML/packnet-sfm#83]
Hi.
First of all, thanks for sharing your great work.

I'd like to reproduce numbers in the paper. However, it seems like the scripts in the repo have slightly different configurations from the paper (e.g., configs/train_kitti.yaml). And I can't find the scripts for several experiments shown in the paper such as scale-aware training and pre-training on Cityscapes.

Would it be possible for you to share scripts for reproducing numbers in the paper with us?

Thanks :)

**Comment by porwalnaman01** [comment]
@hdjang Hello there, did you receive this error while training, if yes then how did you solve it?

Traceback (most recent call last):
File "scripts/train.py", line 68, in
train(args.file)
File "scripts/train.py", line 63, in train
trainer.fit(model_wrapper)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 65, in fit
validation_output = self.validate(val_dataloaders, module)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 120, in validate
output = module.validation_step(batch, i, n)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 194, in validation_step
output = self.evaluate_depth(batch)
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 302, in evaluate_depth
inv_depths[0], inv_depths_flipped[0], method='mean')
File "/disk1/dan/Naman/packnet-sfm/packnet_sfm/utils/depth.py", line 247, in post_process_inv_depth
B,C, H, W = inv_depth.shape
ValueError: not enough values to unpack (expected 4, got 3)
