### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by chaotianjiao** [TRI-ML/packnet-sfm#95]
@VitorGuizilini-TRI Hi~, Thanks for your great paper and code! It's amzaing!  
when I run "python3 scripts/train.py configs/overfit_kitti.yaml", There is some problem like this:
```
### Preparing Model
Model: SelfSupModel
DepthNet: DepthResNet
PoseNet: PoseResNet
### Preparing Datasets
###### Setup train datasets
#########       0 (x1000): /data/datasets/KITTI_tiny/kitti_tiny.txt
###### Setup validation datasets
#########       0: /data/datasets/KITTI_tiny/kitti_tiny.txt
###### Setup test datasets
#########       0: /data/datasets/KITTI_tiny/kitti_tiny.txt

########################################################################################################################
### Config: configs.default_config -> configs.overfit_kitti.yaml
### Name: default_config-overfit_kitti-2020.11.20-07h27m45s
########################################################################################################################
config:
-- name: default_config-overfit_kitti-2020.11.20-07h27m45s
-- debug: False
-- arch:
---- seed: 42
---- min_epochs: 1
---- max_epochs: 1
-- checkpoint:
---- filepath: 
---- save_top_k: 5
---- monitor: loss
---- monitor_index: 0
---- mode: auto
---- s3_path: 
---- s3_frequency: 1
---- s3_url: 
-- save:
---- folder: 
---- depth:
------ rgb: True
------ viz: True
------ npz: True
------ png: True
---- pretrained: 
-- wandb:
---- dry_run: True
---- name: 
---- project: 
---- entity: 
---- tags: []
---- dir: 
---- url: 
-- model:
---- name: SelfSupModel
---- checkpoint_path: 
---- optimizer:
------ name: Adam
------ depth:
-------- lr: 0.0002
-------- weight_decay: 0.0
------ pose:
-------- lr: 0.0002
-------- weight_decay: 0.0
---- scheduler:
------ name: StepLR
------ step_size: 30
------ gamma: 0.5
------ T_max: 20
---- params:
------ crop: garg
------ min_depth: 0.0
------ max_depth: 80.0
---- loss:
------ num_scales: 4
------ progressive_scaling: 0.0
------ flip_lr_prob: 0.5
------ rotation_mode: euler
------ upsample_depth_maps: True
------ ssim_loss_weight: 0.85
------ occ_reg_weight: 0.1
------ smooth_loss_weight: 0.001
------ C1: 0.0001
------ C2: 0.0009
------ photometric_reduce_op: min
------ disp_norm: True
------ clip_loss: 0.0
------ padding_mode: zeros
------ automask_loss: True
------ velocity_loss_weight: 0.1
------ supervised_method: sparse-l1
------ supervised_num_scales: 4
------ supervised_loss_weight: 0.9
---- depth_net:
------ name: DepthResNet
------ checkpoint_path: 
------ version: 18pt
------ dropout: 0.0
---- pose_net:
------ name: PoseResNet
------ checkpoint_path: 
------ version: 18pt
------ dropout: 0.0
-- datasets:
---- augmentation:
------ image_shape: (192, 640)
------ jittering: (0.2, 0.2, 0.2, 0.05)
---- train:
------ batch_size: 6
------ num_workers: 16
------ back_context: 1
------ forward_context: 1
------ dataset: ['KITTI']
------ path: ['/data/datasets/KITTI_tiny']
------ split: ['kitti_tiny.txt']
------ depth_type: ['velodyne']
------ cameras: [[]]
------ repeat: [1000]
------ num_logs: 5
---- validation:
------ batch_size: 1
------ num_workers: 8
------ back_context: 0
------ forward_context: 0
------ dataset: ['KITTI']
------ path: ['/data/datasets/KITTI_tiny']
------ split: ['kitti_tiny.txt']
------ depth_type: ['velodyne']
------ cameras: [[]]
------ num_logs: 5
---- test:
------ batch_size: 1
------ num_workers: 8
------ back_context: 0
------ forward_context: 0
------ dataset: ['KITTI']
------ path: ['/data/datasets/KITTI_tiny']
------ split: ['kitti_tiny.txt']
------ depth_type: ['velodyne']
------ cameras: [[]]
------ num_logs: 5
-- config: configs/overfit_kitti.yaml
-- default: configs/default_config
-- prepared: True
########################################################################################################################
### Config: configs.default_config -> configs.overfit_kitti.yaml
### Name: default_config-overfit_kitti-2020.11.20-07h27m45s
########################################################################################################################

0 images [00:00, ? images/s]
Traceback (most recent call last):
  File "scripts/train.py", line 64, in <module>
    train(args.file)
  File "scripts/train.py", line 59, in train
    trainer.fit(model_wrapper)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 58, in fit
    self.train(train_dataloader, module, optimizer)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 98, in train
    return module.training_epoch_end(outputs)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 219, in training_epoch_end
    loss_and_metrics = average_loss_and_metrics(output_batch, 'avg_train')
  File "/workspace/packnet-sfm/packnet_sfm/utils/reduce.py", line 215, in average_loss_and_metrics
    average_key(batch_list, key)
  File "/workspace/packnet-sfm/packnet_sfm/utils/reduce.py", line 173, in average_key
    return sum(values) / len(values)
ZeroDivisionError: division by zero
```
where should I modify my code?
Thanks again!~

**Comment by VitorGuizilini-TRI** [comment]
Hi, it seems like the datasets are not being found (you are getting 0 as dataset size for train/val/test). Can you check if the paths are correctly set up? That should solve it!

**Comment by chaotianjiao** [comment]
@VitorGuizilini-TRI Hi~
This is my PC's folder:
![image](https://user-images.githubusercontent.com/42534375/99924645-12384300-2d76-11eb-90c5-da96e2677b69.png)
This is my docker's folder:
![image](https://user-images.githubusercontent.com/42534375/99924693-3ac03d00-2d76-11eb-8563-0f7d85a78cf1.png)
In my PC I have tried  `docker cp /home/felix/Files/github_projects/packnet-sfm packnet-sfm:/workspace/packnet-sfm`
and change the dataset.py like this:
![image](https://user-images.githubusercontent.com/42534375/99924889-f97c5d00-2d76-11eb-858c-ae69a6c285ba.png)
But still get ZeroDivisionError: division by zero.
If I don't change the dataset.py, I would get another error:
![image](https://user-images.githubusercontent.com/42534375/99925052-81626700-2d77-11eb-91e4-38f63e194ae7.png)
Which step do I wrong?
Great thanks~

**Comment by VitorGuizilini-TRI** [comment]
Hmm, I think your `data` folder is inside the root folder of `packnet-sfm`, it should be on the root folder of your system (hence the initial `/` in `/data/datasets`). Can you try removing it, or moving the `data` folder to the root folder of the system?

**Comment by chaotianjiao** [comment]
It works~,Thank you~
